### ISSUE TITLE
CubaSUAVE returning wrong result, NaN

### ISSUE THREAD

**Issue by agerlach** [SciML/Quadrature.jl#17]
`suave()` from Cuba.jl  is not handling large `maxiters` properly. See [issue](https://github.com/giordano/Cuba.jl/issues/27).

Currently Quadtrature.jl sets by default, `maxiters = typemax(Int)`. I recommend changing the default to the default used by Cuba.jl, `maxiters = 1000000`

**Comment by ChrisRackauckas** [comment]
Interesting that it needs needs. Yeah, setting the default maxiters so it works would be good.

**Comment by agerlach** [comment]
This is fixed in #20
