### ISSUE TITLE
Integrand definition for batch evaluations

### ISSUE THREAD

**Issue by agerlach** [SciML/Quadrature.jl#19]
Right now it looks like the integrand needs to be written specially to handle batch evaluation. Can we update the batch evaluation to work of off broadcast instead so the integrand doesn't need to be "batch aware"?

How does this impact GPU support?

**Comment by ChrisRackauckas** [comment]
We wouldn't be able to support GPUs if it's done with broadcast. We need the batch evaluation form to have the control to allow for these kinds of features.
