### ISSUE TITLE
Passing data to function

### ISSUE THREAD

**Issue by fintzij** [SciML/Quadrature.jl#79]
Hello,

I have a function that I would like to integrate repeatedly but which depends on data whose values might change. Is there a way to specify a function in Quadrature.jl such that I don't need to create a new QuadratureProblem each time the values of the data change?

For example, is there a way to pass `f(x, p, d) = sum(sin.(x * p + d))` so that I could change the value of `d` in an outer loop and just call `solve()` instead of creating a new QuadratureProblem each time? 

Apologies in advance if this is obvious and there is something trivial I am overlooking.

Thanks,
Jon

**Comment by ChrisRackauckas** [comment]
So `d` is the parameter? Why not make the parameters `p`?

**Comment by fintzij** [comment]
So, for a bit more context, this is part of a statistical package. `d` are data in the sense that the values are known, not estimated, like covariates. `p` are parameters that are being estimated, so, e.g., we would want autodiff to be taking gradients with respect to `p` but not `d`. Zooming out a bit, `d` might be a row in a dataset that we want to pass as an argument to `f()`

**Comment by fintzij** [comment]
One more point is that we'd like to handle the data with some generality so that we have a general modeling framework. Obviously, it is trivial to hard code the values when they're known ahead of time.

**Comment by ChrisRackauckas** [comment]
You can use a closure then. `f(x, p) = sum(sin.(x * p + d))` just enclose
